version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: simi-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      DB_HOST: simi-rds.ccnvfj1nlf96.us-east-1.rds.amazonaws.com
      DB_NAME: simi_erp
      DB_USER: postgres
      DB_PASS: simi_pass123
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: us-east-1
      S3_BUCKET: simi-backups
      JWT_SECRET: simi_secret_key_2026
      TOTP_ENCRYPTION_KEY: ${totp_encryption_key}
networks:
  simi-net:
    driver: bridge